default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
  pool: 5

development:
  <<: *default
  database: carlosflix_development

# production:
#   primary: &primary_production
#     <<: *default
#     database: carlosflix_production
#     username: carlosflix
#     password: <%= ENV["CARLOSFLIX_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: carlosflix_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: carlosflix_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: carlosflix_production_cable
#     migrations_paths: db/cable_migrate
